config/routes.rb
Rails::application.routes.draw do
  resources :employees
  resources :companies do
  	collection { post :import }
  end	

  devise_for :users
  get 'welcome/index'

  get 'welcome/about'

  get 'welcome/contact'

  get 'welcome/features'

  get 'welcome/login'

  resources :invoices do
    resources :purchases, except: [:index], controller: 'invoices/purchases'
  end  

  root to:'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :employee
  has_many :purchases, dependent: :destroy 
end

app/controllers/invoices/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]

  # GET /purchases
  # GET /purchases.json
  def index
    @purchases = Purchase.all
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
  end

  # GET /purchases/new
  def new
    @purchase = Purchase.new
  end

  # GET /purchases/1/edit
  def edit
  end

  # POST /purchases
  # POST /purchases.json
  def create
    @purchase = Purchase.new(purchase_params)

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to @purchase, notice: 'Purchase was successfully created.' }
        format.json { render :show, status: :created, location: @purchase }
      else
        format.html { render :new }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1
  # PATCH/PUT /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to @purchase, notice: 'Purchase was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    @purchase.destroy
    respond_to do |format|
      format.html { redirect_to purchases_url, notice: 'Purchase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_params
      params.require(:purchase).permit(:name, :category, :quantity, :invoice_id)
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @search = InvoiceSearch.new(params[:search])
    @invoices = @search.scope
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
    @invoice = Invoice.find(params[:id])
    @purchases = @invoice.purchases
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:date, :company, :tax, :employee_id, :status_type)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<div class="row">
<%= form_for @invoice, html: {class: 'form-horizontal'} do |f| %>
                                                                          <!--f=form -->
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :date, class: 'control-label' %><br>
    <div class="controls">
      <%= f.datetime_select :date, id: :invoice_date %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :company, class: 'control-label' %><br>
    <div class="controls">
      <%= f.text_field :company, id: :invoice_company %>
    </div>  
  </div>

  <div class="control-group">
    <%= f.label :tax, class: 'control-label' %><br>
    <div class="controls">
      <%= f.text_field :tax, id: :invoice_tax %>
    </div>  
  </div>

  <div class="control-group">
    <%= f.label :employee_id, class: 'control-label' %><br>
    <div class="controls">
      <%= collection_select( :invoice, :employee_id, Employee.all, :id, :name, {}, { :multiple => false}) %>
    </div>  
  </div>
 
  <div class="control-group">
    <%= f.label "status", class: 'control-label' %>
    <div class="controls">
      <%= f.select(:status_type, options_for_select([['PAID','PAID'],['PENDING','PENDING'],['CANCEL','CANCEL']])) %><!-- in two paid and two pendings are writing as 1.is database and 2. is user seeing thats purpose on writing two times-->
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.submit 'submit', class: 'btn btn-default'%>
    </div>  
  </div>
</div>  
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
 
<div class="row"> 
  <div class="pull-right range-query">
    <%=form_tag invoices_path, method: :get do %>
      <%= text_field_tag 'search[date_from]', @search.date_from %>
      <%= text_field_tag 'search[date_to]', @search.date_to %>
      <%= submit_tag 'search', class: 'btn search-button' %>
    <% end %>
  </div>
<div> 
<h1>Listing Invoices</h1>
<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Date</th>
          <th>Company</th>
          <th>Tax</th>
          <th>Salesperson</th>
          <th>Status</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @invoices.each do |invoice| %>
          <tr>
            <td><%= invoice.date.strftime("%y-%m-%d") %></td>
            <td><%= invoice.company %></td>
            <td><%= invoice.tax %></td>
            <td><%= invoice.employee_id %></td>
            <td><%= invoice.status_type %></td>
            <td><%= link_to 'Show', invoice, class: 'btn btn-mini'%></td>
            <td><%= link_to 'Edit', edit_invoice_path(invoice), class: 'btn btn-mini btn-success' %></td>
            <td><%= link_to 'Destroy', invoice, method: :delete, class: 'btn btn-mini btn-danger',data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p>
  <strong>Date:</strong>
  <%= @invoice.date %>
</p>

<p>
  <strong>Company:</strong>
  <%= @invoice.company %>
</p>

<p>
  <strong>Tax:</strong>
  <%= @invoice.tax %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @invoice.employee.name %>
</p>

<div class="media">
	<div class="media-body">
		<table class="table table-hover">
			<thead>
				<tr>
					<th>Name</th>
					<th>Category</th>
					<th>Quantity</th>
				</tr>
			</thead>
			<tbody>
				<% @purchases.each do |purchase| %>
				  <tr>
				  	<td><h4><%= purchase.name %></h4></td>
				  	<td><h4><%= purchase.category %></h4></td>
				  	<td><h4><%= purchase.quantity %></h4></td>
				  </tr>
				<% end %>  
			</tbody>
		</table>
	</div>
</div>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>