config/routes.rb
Rails::application.routes.draw do
  resources :employees
  resources :companies do
  	collection { post :import }
  end	

  devise_for :users
  get 'welcome/index'

  get 'welcome/about'

  get 'welcome/contact'

  get 'welcome/features'

  get 'welcome/login'

  resources :invoices do
    resources :purchases, except: [:index], controller: 'invoices/purchases'
  end  

  root to:'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Start</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<div class="container">
  <ul class="nav nav-tabs">
    <li><%= link_to "Home",root_path %></li> 
    <li><%= link_to "About",welcome_about_path %></li>
    <li><%= link_to "Contact",welcome_contact_path %></li>
    <li><%= link_to "Features",welcome_features_path %></li>
    <li><%= link_to "Invoices",invoices_path %></li>
    <li><%= link_to "Companies",companies_path %></li>
    <li><%= link_to "Employees",employees_path %></li>
    
    <% if current_user %>
      <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
      <div class='btn-group pull-right right-nav'>
        <button type="button" class="btn btn-mini dropdown-toggle" data-toggle="dropdown">
          <span class="caret"></span>
          <span clas="sr-only">Admin</span>
        </button>
       <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Invoices",invoices_path %></li>
          <li><%= link_to "Companies",companies_path %></li>
          <li><%= link_to "Employees",employees_path %></li>
       </ul>
      </div>
    <% else %>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <li><%= link_to "Log In", new_user_session_path %></li>
    <% end %>  
  </ul>
   
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:error] %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
   <% end %>   
        
  <%= yield %>
</div> 
 </body>
</html>